In [257]:
import pandas as pd
import numpy as np

In [258]:
df=pd.read_csv("/content/Churn_Modelling.csv")

In [259]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [260]:
df.shape

(10000, 14)

In [261]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [262]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [263]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [264]:
X=df.iloc[:,3:13]
Y=df.iloc[:,13]

In [265]:
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [266]:
Y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [267]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [268]:
X_train.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
3272,728,France,Female,59,4,0.00,1,1,1,163365.85
5417,588,France,Male,32,1,0.00,2,1,1,8763.87
618,546,Spain,Male,42,7,139070.51,1,1,1,86945.00
8067,530,France,Female,29,5,0.00,2,0,0,121451.21
7882,850,Germany,Female,45,1,121874.89,1,0,0,6865.41

In [269]:
Y_train.head()

3272    1
5417    0
618     0
8067    0
7882    1
Name: Exited, dtype: int64

In [270]:
X_test.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
8182,562,Spain,Male,36,5,0.00,1,0,1,182843.24
9040,581,Germany,Female,38,3,135157.05,1,1,1,32919.42
5376,850,Spain,Male,38,1,146343.98,1,0,1,103902.11
4250,489,France,Female,38,5,117289.92,1,0,0,85231.88
6690,573,Germany,Male,30,8,127406.50,1,1,0,192950.60

In [271]:
X_test.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
8182,562,Spain,Male,36,5,0.00,1,0,1,182843.24
9040,581,Germany,Female,38,3,135157.05,1,1,1,32919.42
5376,850,Spain,Male,38,1,146343.98,1,0,1,103902.11
4250,489,France,Female,38,5,117289.92,1,0,0,85231.88
6690,573,Germany,Male,30,8,127406.50,1,1,0,192950.60

In [272]:
X_train.shape

(8000, 10)

In [273]:
Y_train.shape

(8000,)

In [274]:
X_test.shape

(2000, 10)

In [275]:
Y_test.shape

(2000,)

In [276]:
numerical_column=['CreditScore','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary']
categorical_column=['Geography','Gender']

In [277]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_column),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_column)
    ]
)

In [278]:
X_train = preprocessor.fit_transform(X_train)

In [279]:
X_test = preprocessor.transform(X_test)

In [280]:
X_train

array([[ 0.80497615,  1.90337168, -0.34070592, ...,  0.        ,
         1.        ,  0.        ],
       [-0.64382543, -0.6613232 , -1.3794435 , ...,  0.        ,
         0.        ,  1.        ],
       [-1.07846591,  0.28856379,  0.69803165, ...,  1.        ,
         0.        ,  1.        ],
       ...,
       [-0.59208252,  0.0035977 , -1.72568936, ...,  0.        ,
         1.        ,  0.        ],
       [-0.78870559, -0.5663345 , -0.68695178, ...,  0.        ,
         1.        ,  0.        ],
       [-0.35406512,  3.04323607, -0.34070592, ...,  1.        ,
         0.        ,  1.        ]])

In [281]:
X_test

array([[-0.91288858, -0.2813684 ,  0.00553993, ...,  1.        ,
         0.        ,  1.        ],
       [-0.71626551, -0.091391  , -0.68695178, ...,  0.        ,
         1.        ,  0.        ],
       [ 2.06750324, -0.091391  , -1.3794435 , ...,  1.        ,
         0.        ,  1.        ],
       ...,
       [ 0.41173001, -0.3763571 ,  1.39052337, ...,  0.        ,
         1.        ,  0.        ],
       [-0.86114567, -0.4713458 ,  1.73676923, ...,  1.        ,
         0.        ,  1.        ],
       [ 2.06750324, -0.2813684 ,  0.35178579, ...,  0.        ,
         1.        ,  0.        ]])

In [282]:
Y_train=np.array(Y_train)
Y_test=np.array(Y_test)

In [283]:
Y_train

array([1, 0, 0, ..., 0, 0, 0])

In [284]:
Y_test

array([0, 0, 0, ..., 0, 0, 0])

In [295]:
np.save('X_train.npy', X_train)

In [296]:
np.save('X_test.npy', X_test)

In [297]:
np.save('Y_train.npy', Y_train)

In [298]:
np.save('Y_test.npy', Y_test)